version: "3.9"

services:
  backend:
    build: ./Backend
    ports:
      - "4000:4000"
    env_file:
      - ./Backend/.env
    depends_on:
      - redis-cache
      - redis-queue
    restart: unless-stopped

  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  redis-cache:
    image: redis:7-alpine
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-cache-data:/data

  redis-queue:
    image: redis:7-alpine
    container_name: redis-queue
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis-queue-data:/data

volumes:
  redis-cache-data:
  redis-queue-data: